################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
virt/lib \
virt/kvm \
virt/kvm/arm \
virt \
usr \
tools/vm \
tools/virtio \
tools/virtio/virtio-trace \
tools/virtio/vhost_test \
tools/usb/usbip/src \
tools/usb/usbip/libsrc \
tools/usb \
tools/usb/ffs-aio-example/simple/host_app \
tools/usb/ffs-aio-example/simple/device_app \
tools/usb/ffs-aio-example/multibuff/host_app \
tools/usb/ffs-aio-example/multibuff/device_app \
tools/thermal/tmon \
tools/testing/selftests/x86 \
tools/testing/selftests/vm \
tools/testing/selftests/timers \
tools/testing/selftests/size \
tools/testing/selftests/seccomp \
tools/testing/selftests/ptrace \
tools/testing/selftests/powerpc/vphn \
tools/testing/selftests/powerpc/tm \
tools/testing/selftests/powerpc/syscalls \
tools/testing/selftests/powerpc/switch_endian \
tools/testing/selftests/powerpc/stringloops \
tools/testing/selftests/powerpc/primitives \
tools/testing/selftests/powerpc/pmu \
tools/testing/selftests/powerpc/pmu/ebb \
tools/testing/selftests/powerpc/mm \
tools/testing/selftests/powerpc \
tools/testing/selftests/powerpc/dscr \
tools/testing/selftests/powerpc/copyloops \
tools/testing/selftests/powerpc/benchmarks \
tools/testing/selftests/net \
tools/testing/selftests/mqueue \
tools/testing/selftests/mount \
tools/testing/selftests/memfd \
tools/testing/selftests/membarrier \
tools/testing/selftests/kcmp \
tools/testing/selftests/ipc \
tools/testing/selftests/futex/functional \
tools/testing/selftests/exec \
tools/testing/selftests/efivarfs \
tools/testing/selftests/capabilities \
tools/testing/selftests/breakpoints \
tools/testing/nvdimm/test \
tools/testing/nvdimm \
tools/power/x86/x86_energy_perf_policy \
tools/power/x86/turbostat \
tools/power/cpupower/utils/idle_monitor \
tools/power/cpupower/utils/helpers \
tools/power/cpupower/utils \
tools/power/cpupower/lib \
tools/power/cpupower/debug/kernel \
tools/power/cpupower/debug/i386 \
tools/power/cpupower/bench \
tools/power/acpi/tools/ec \
tools/power/acpi/tools/acpidump \
tools/power/acpi/os_specific/service_layers \
tools/power/acpi/common \
tools/perf/util \
tools/perf/util/scripting-engines \
tools/perf/util/intel-pt-decoder \
tools/perf/ui \
tools/perf/ui/tui \
tools/perf/ui/stdio \
tools/perf/ui/gtk \
tools/perf/ui/browsers \
tools/perf/tests \
tools/perf/scripts/python/Perf-Trace-Util \
tools/perf/scripts/perl/Perf-Trace-Util \
tools/perf \
tools/perf/bench \
tools/perf/arch/xtensa/util \
tools/perf/arch/x86/util \
tools/perf/arch/x86/tests \
tools/perf/arch/sparc/util \
tools/perf/arch/sh/util \
tools/perf/arch/s390/util \
tools/perf/arch/powerpc/util \
tools/perf/arch \
tools/perf/arch/arm64/util \
tools/perf/arch/arm64/tests \
tools/perf/arch/arm/util \
tools/perf/arch/arm/tests \
tools/net \
tools/lib/util \
tools/lib/traceevent \
tools/lib/symbol \
tools/lib \
tools/lib/lockdep/tests \
tools/lib/lockdep \
tools/lib/bpf \
tools/lib/api/fs \
tools/lib/api/fd \
tools/lib/api \
tools/lguest \
tools/laptop/freefall \
tools/iio \
tools/hv \
tools/firewire \
tools/cgroup \
tools/build/tests/ex \
tools/build/tests/ex/arch \
tools/build \
tools/build/feature \
sound/usb/usx2y \
sound/usb \
sound/usb/misc \
sound/usb/line6 \
sound/usb/hiface \
sound/usb/caiaq \
sound/usb/bcd2000 \
sound/usb/6fire \
sound/synth \
sound/synth/emux \
sound/spi \
sound/sparc \
sound \
sound/soc/zte \
sound/soc/xtensa \
sound/soc/ux500 \
sound/soc/txx9 \
sound/soc/tegra \
sound/soc/sunxi \
sound/soc/sti \
sound/soc/spear \
sound/soc \
sound/soc/sirf \
sound/soc/sh \
sound/soc/sh/rcar \
sound/soc/samsung \
sound/soc/rockchip \
sound/soc/qcom \
sound/soc/pxa \
sound/soc/omap \
sound/soc/nuc900 \
sound/soc/mxs \
sound/soc/mediatek \
sound/soc/kirkwood \
sound/soc/jz4740 \
sound/soc/intel/skylake \
sound/soc/intel/haswell \
sound/soc/intel/common \
sound/soc/intel \
sound/soc/intel/boards \
sound/soc/intel/baytrail \
sound/soc/intel/atom \
sound/soc/intel/atom/sst \
sound/soc/generic \
sound/soc/fsl \
sound/soc/dwc \
sound/soc/davinci \
sound/soc/codecs \
sound/soc/cirrus \
sound/soc/blackfin \
sound/soc/bcm \
sound/soc/au1x \
sound/soc/atmel \
sound/soc/adi \
sound/sh \
sound/ppc \
sound/pcmcia/vx \
sound/pcmcia/pdaudiocf \
sound/pcmcia \
sound/pci/ymfpci \
sound/pci/vx222 \
sound/pci \
sound/pci/trident \
sound/pci/rme9652 \
sound/pci/riptide \
sound/pci/pcxhr \
sound/pci/oxygen \
sound/pci/nm256 \
sound/pci/mixart \
sound/pci/lx6464es \
sound/pci/lola \
sound/pci/korg1212 \
sound/pci/ice1712 \
sound/pci/hda \
sound/pci/emu10k1 \
sound/pci/echoaudio \
sound/pci/ctxfi \
sound/pci/cs5535audio \
sound/pci/cs46xx \
sound/pci/ca0106 \
sound/pci/aw2 \
sound/pci/au88x0 \
sound/pci/asihpi \
sound/pci/ali5451 \
sound/pci/ac97 \
sound/parisc \
sound/oss \
sound/oss/dmasound \
sound/mips \
sound/isa/wss \
sound/isa/wavefront \
sound/isa \
sound/isa/sb \
sound/isa/opti9xx \
sound/isa/msnd \
sound/isa/gus \
sound/isa/galaxy \
sound/isa/es1688 \
sound/isa/cs423x \
sound/isa/ad1848 \
sound/isa/ad1816a \
sound/i2c \
sound/i2c/other \
sound/hda \
sound/hda/ext \
sound/firewire/tascam \
sound/firewire \
sound/firewire/oxfw \
sound/firewire/fireworks \
sound/firewire/digi00x \
sound/firewire/dice \
sound/firewire/bebob \
sound/drivers/vx \
sound/drivers \
sound/drivers/pcsp \
sound/drivers/opl4 \
sound/drivers/opl3 \
sound/drivers/mpu401 \
sound/core \
sound/core/seq \
sound/core/seq/oss \
sound/core/oss \
sound/atmel \
sound/arm \
sound/aoa/soundbus \
sound/aoa/soundbus/i2sbus \
sound/aoa/fabrics \
sound/aoa/core \
sound/aoa/codecs \
security/yama \
security/tomoyo \
security/smack \
security/selinux \
security/selinux/ss \
security \
security/keys \
security/keys/encrypted-keys \
security/integrity \
security/integrity/ima \
security/integrity/evm \
security/apparmor \
scripts \
scripts/selinux/mdp \
scripts/selinux/genheaders \
scripts/mod \
scripts/kconfig \
scripts/kconfig/lxdialog \
scripts/genksyms \
scripts/dtc \
scripts/dtc/libfdt \
scripts/basic \
samples/uhid \
samples/trace_events \
samples/seccomp \
samples/rpmsg \
samples/mic/mpssd \
samples/livepatch \
samples/kprobes \
samples/kobject \
samples/kfifo \
samples/kdb \
samples/hw_breakpoint \
samples/hidraw \
samples/configfs \
samples/bpf \
net/xfrm \
net/x25 \
net/wireless \
net/wimax \
net/vmw_vsock \
net/unix \
net/tipc \
net \
net/switchdev \
net/sunrpc \
net/sunrpc/xprtrdma \
net/sunrpc/auth_gss \
net/sctp \
net/sched \
net/rxrpc \
net/rose \
net/rfkill \
net/rds \
net/phonet \
net/packet \
net/openvswitch \
net/nfc \
net/nfc/nci \
net/nfc/hci \
net/netrom \
net/netlink \
net/netlabel \
net/netfilter \
net/netfilter/ipvs \
net/netfilter/ipset \
net/mpls \
net/mac802154 \
net/mac80211 \
net/llc \
net/lapb \
net/l3mdev \
net/l2tp \
net/key \
net/iucv \
net/irda \
net/irda/irnet \
net/irda/irlan \
net/irda/ircomm \
net/ipx \
net/ipv6 \
net/ipv6/netfilter \
net/ipv4 \
net/ipv4/netfilter \
net/ieee802154 \
net/ieee802154/6lowpan \
net/hsr \
net/ethernet \
net/dsa \
net/dns_resolver \
net/decnet \
net/decnet/netfilter \
net/dccp \
net/dccp/ccids/lib \
net/dccp/ccids \
net/dcb \
net/core \
net/ceph \
net/ceph/crush \
net/can \
net/caif \
net/bridge/netfilter \
net/bridge \
net/bluetooth \
net/bluetooth/rfcomm \
net/bluetooth/hidp \
net/bluetooth/cmtp \
net/bluetooth/bnep \
net/batman-adv \
net/ax25 \
net/atm \
net/appletalk \
net/9p \
net/8021q \
net/802 \
net/6lowpan \
mm \
mm/kasan \
lib/zlib_inflate \
lib/zlib_deflate \
lib/xz \
lib \
lib/reed_solomon \
lib/raid6/test \
lib/raid6 \
lib/mpi \
lib/lzo \
lib/lz4 \
lib/fonts \
lib/842 \
kernel \
kernel/trace \
kernel/time \
kernel/sched \
kernel/rcu \
kernel/printk \
kernel/power \
kernel/locking \
kernel/livepatch \
kernel/irq \
kernel/gcov \
kernel/events \
kernel/debug/kdb \
kernel/debug \
kernel/bpf \
ipc \
init \
include/uapi/asm-generic \
include/asm-generic \
fs/xfs \
fs/xfs/libxfs \
fs \
fs/ufs \
fs/udf \
fs/ubifs \
fs/tracefs \
fs/sysv \
fs/sysfs \
fs/squashfs \
fs/romfs \
fs/reiserfs \
fs/ramfs \
fs/quota \
fs/qnx6 \
fs/qnx4 \
fs/pstore \
fs/proc \
fs/overlayfs \
fs/openpromfs \
fs/omfs \
fs/ocfs2 \
fs/ocfs2/dlmfs \
fs/ocfs2/dlm \
fs/ocfs2/cluster \
fs/ntfs \
fs/notify \
fs/notify/inotify \
fs/notify/fanotify \
fs/notify/dnotify \
fs/nls \
fs/nilfs2 \
fs/nfsd \
fs/nfs_common \
fs/nfs \
fs/nfs/objlayout \
fs/nfs/flexfilelayout \
fs/nfs/filelayout \
fs/nfs/blocklayout \
fs/ncpfs \
fs/minix \
fs/logfs \
fs/lockd \
fs/kernfs \
fs/jfs \
fs/jffs2 \
fs/jbd2 \
fs/isofs \
fs/hugetlbfs \
fs/hpfs \
fs/hostfs \
fs/hfsplus \
fs/hfs \
fs/gfs2 \
fs/fuse \
fs/fscache \
fs/freevxfs \
fs/fat \
fs/f2fs \
fs/ext4 \
fs/ext2 \
fs/exportfs \
fs/exofs \
fs/efs \
fs/efivarfs \
fs/ecryptfs \
fs/dlm \
fs/devpts \
fs/debugfs \
fs/cramfs \
fs/configfs \
fs/coda \
fs/cifs \
fs/ceph \
fs/cachefiles \
fs/btrfs \
fs/btrfs/tests \
fs/bfs \
fs/befs \
fs/autofs4 \
fs/afs \
fs/affs \
fs/adfs \
fs/9p \
firmware/keyspan_pda \
firmware/keyspan \
firmware \
firmware/dsp56k \
firmware/av7110 \
drivers/zorro \
drivers/xen \
drivers/xen/xenfs \
drivers/xen/xenbus \
drivers/xen/xen-pciback \
drivers/xen/events \
drivers/watchdog \
drivers/w1 \
drivers/w1/slaves \
drivers/w1/masters \
drivers/vme \
drivers/vme/bridges \
drivers/vme/boards \
drivers/vlynq \
drivers/virtio \
drivers/virt \
drivers/video \
drivers/video/logo \
drivers/video/fbdev \
drivers/video/fbdev/via \
drivers/video/fbdev/vermilion \
drivers/video/fbdev/sis \
drivers/video/fbdev/savage \
drivers/video/fbdev/riva \
drivers/video/fbdev/omap2 \
drivers/video/fbdev/omap2/omapfb \
drivers/video/fbdev/omap2/dss \
drivers/video/fbdev/omap2/displays-new \
drivers/video/fbdev/omap \
drivers/video/fbdev/nvidia \
drivers/video/fbdev/mmp/panel \
drivers/video/fbdev/mmp/hw \
drivers/video/fbdev/mmp/fb \
drivers/video/fbdev/mmp \
drivers/video/fbdev/mbx \
drivers/video/fbdev/mb862xx \
drivers/video/fbdev/matrox \
drivers/video/fbdev/kyro \
drivers/video/fbdev/intelfb \
drivers/video/fbdev/i810 \
drivers/video/fbdev/geode \
drivers/video/fbdev/exynos \
drivers/video/fbdev/core \
drivers/video/fbdev/aty \
drivers/video/console \
drivers/video/backlight \
drivers/vhost \
drivers/vfio \
drivers/vfio/platform \
drivers/vfio/platform/reset \
drivers/vfio/pci \
drivers/uwb \
drivers/uwb/i1480 \
drivers/uwb/i1480/dfu \
drivers/usb/wusbcore \
drivers/usb/usbip \
drivers/usb \
drivers/usb/storage \
drivers/usb/serial \
drivers/usb/renesas_usbhs \
drivers/usb/phy \
drivers/usb/musb \
drivers/usb/mon \
drivers/usb/misc \
drivers/usb/misc/sisusbvga \
drivers/usb/isp1760 \
drivers/usb/image \
drivers/usb/host \
drivers/usb/host/whci \
drivers/usb/gadget \
drivers/usb/gadget/udc \
drivers/usb/gadget/udc/bdc \
drivers/usb/gadget/legacy \
drivers/usb/gadget/function \
drivers/usb/early \
drivers/usb/dwc3 \
drivers/usb/dwc2 \
drivers/usb/core \
drivers/usb/common \
drivers/usb/class \
drivers/usb/chipidea \
drivers/usb/c67x00 \
drivers/usb/atm \
drivers/uio \
drivers/tty/vt \
drivers/tty \
drivers/tty/serial \
drivers/tty/serial/jsm \
drivers/tty/serial/cpm_uart \
drivers/tty/serial/8250 \
drivers/tty/ipwireless \
drivers/tty/hvc \
drivers/thunderbolt \
drivers/thermal \
drivers/thermal/ti-soc-thermal \
drivers/thermal/st \
drivers/thermal/samsung \
drivers/thermal/int340x_thermal \
drivers/tc \
drivers/target/tcm_fc \
drivers/target \
drivers/target/sbp \
drivers/target/loopback \
drivers/target/iscsi \
drivers/staging/xgifb \
drivers/staging/wlan-ng \
drivers/staging/wilc1000 \
drivers/staging/vt6656 \
drivers/staging/vt6655 \
drivers/staging/vme/devices \
drivers/staging/vme \
drivers/staging/unisys/visornic \
drivers/staging/unisys/visorinput \
drivers/staging/unisys/visorhba \
drivers/staging/unisys/visorbus \
drivers/staging/unisys \
drivers/staging/ste_rmi4 \
drivers/staging \
drivers/staging/speakup \
drivers/staging/sm750fb \
drivers/staging/slicoss \
drivers/staging/skein \
drivers/staging/rts5208 \
drivers/staging/rtl8723au \
drivers/staging/rtl8723au/os_dep \
drivers/staging/rtl8723au/hal \
drivers/staging/rtl8723au/core \
drivers/staging/rtl8712 \
drivers/staging/rtl8192u \
drivers/staging/rtl8192u/ieee80211 \
drivers/staging/rtl8192e \
drivers/staging/rtl8192e/rtl8192e \
drivers/staging/rtl8188eu \
drivers/staging/rtl8188eu/os_dep \
drivers/staging/rtl8188eu/hal \
drivers/staging/rtl8188eu/core \
drivers/staging/rdma/ipath \
drivers/staging/rdma/hfi1 \
drivers/staging/rdma/ehca \
drivers/staging/rdma \
drivers/staging/rdma/amso1100 \
drivers/staging/panel \
drivers/staging/olpc_dcon \
drivers/staging/octeon-usb \
drivers/staging/octeon \
drivers/staging/nvec \
drivers/staging/netlogic \
drivers/staging/mt29f_spinand \
drivers/staging/most/mostcore \
drivers/staging/most/hdm-usb \
drivers/staging/most/hdm-i2c \
drivers/staging/most/hdm-dim2 \
drivers/staging/most \
drivers/staging/most/aim-v4l2 \
drivers/staging/most/aim-sound \
drivers/staging/most/aim-network \
drivers/staging/most/aim-cdev \
drivers/staging/media/omap4iss \
drivers/staging/media/mn88473 \
drivers/staging/media/mn88472 \
drivers/staging/media/lirc \
drivers/staging/media/davinci_vpfe \
drivers/staging/media/cxd2099 \
drivers/staging/media \
drivers/staging/media/bcm2048 \
drivers/staging/lustre/lustre/ptlrpc \
drivers/staging/lustre/lustre/osc \
drivers/staging/lustre/lustre/obdecho \
drivers/staging/lustre/lustre/obdclass \
drivers/staging/lustre/lustre/obdclass/linux \
drivers/staging/lustre/lustre/mgc \
drivers/staging/lustre/lustre/mdc \
drivers/staging/lustre/lustre/lov \
drivers/staging/lustre/lustre/lmv \
drivers/staging/lustre/lustre/llite \
drivers/staging/lustre/lustre/libcfs \
drivers/staging/lustre/lustre/libcfs/linux \
drivers/staging/lustre/lustre/ldlm \
drivers/staging/lustre/lustre/lclient \
drivers/staging/lustre/lustre/fld \
drivers/staging/lustre/lustre/fid \
drivers/staging/lustre/lnet/selftest \
drivers/staging/lustre/lnet/lnet \
drivers/staging/lustre/lnet/klnds/socklnd \
drivers/staging/lustre/lnet/klnds/o2iblnd \
drivers/staging/iio/trigger \
drivers/staging/iio/resolver \
drivers/staging/iio/meter \
drivers/staging/iio/magnetometer \
drivers/staging/iio/light \
drivers/staging/iio/impedance-analyzer \
drivers/staging/iio \
drivers/staging/iio/gyro \
drivers/staging/iio/frequency \
drivers/staging/iio/cdc \
drivers/staging/iio/addac \
drivers/staging/iio/adc \
drivers/staging/iio/accel \
drivers/staging/gs_fpgaboot \
drivers/staging/goldfish \
drivers/staging/gdm72xx \
drivers/staging/gdm724x \
drivers/staging/fwserial \
drivers/staging/fsl-mc/bus \
drivers/staging/fbtft \
drivers/staging/emxx_udc \
drivers/staging/dgnc \
drivers/staging/dgap \
drivers/staging/comedi \
drivers/staging/comedi/kcomedilib \
drivers/staging/comedi/drivers \
drivers/staging/comedi/drivers/addi-data \
drivers/staging/clocking-wizard \
drivers/staging/board \
drivers/staging/android \
drivers/staging/android/ion/tegra \
drivers/staging/android/ion \
drivers/ssb \
drivers/spmi \
drivers/spi \
drivers/soc/versatile \
drivers/soc/ti \
drivers/soc/tegra \
drivers/soc/tegra/fuse \
drivers/soc/sunxi \
drivers/soc/rockchip \
drivers/soc/qcom \
drivers/soc/mediatek \
drivers/soc/dove \
drivers/soc \
drivers/soc/brcmstb \
drivers/sn \
drivers/sh/superhyway \
drivers/sh \
drivers/sh/maple \
drivers/sh/intc \
drivers/sh/clk \
drivers/sfi \
drivers/scsi \
drivers/scsi/ufs \
drivers/scsi/sym53c8xx_2 \
drivers/scsi/snic \
drivers/scsi/qla4xxx \
drivers/scsi/qla2xxx \
drivers/scsi/pm8001 \
drivers/scsi/pcmcia \
drivers/scsi/osd \
drivers/scsi/mvsas \
drivers/scsi/mpt3sas \
drivers/scsi/megaraid \
drivers/scsi/lpfc \
drivers/scsi/libsas \
drivers/scsi/libfc \
drivers/scsi/isci \
drivers/scsi/ibmvscsi \
drivers/scsi/fnic \
drivers/scsi/fcoe \
drivers/scsi/esas2r \
drivers/scsi/device_handler \
drivers/scsi/cxlflash \
drivers/scsi/cxgbi \
drivers/scsi/cxgbi/cxgb4i \
drivers/scsi/cxgbi/cxgb3i \
drivers/scsi/csiostor \
drivers/scsi/bnx2i \
drivers/scsi/bnx2fc \
drivers/scsi/bfa \
drivers/scsi/be2iscsi \
drivers/scsi/arm \
drivers/scsi/arcmsr \
drivers/scsi/aic94xx \
drivers/scsi/aic7xxx \
drivers/scsi/aic7xxx/aicasm \
drivers/scsi/aacraid \
drivers/sbus/char \
drivers/s390/virtio \
drivers/s390/scsi \
drivers/s390/net \
drivers/s390/crypto \
drivers/s390/cio \
drivers/s390/char \
drivers/s390/block \
drivers/rtc \
drivers/rpmsg \
drivers/reset/sti \
drivers/reset \
drivers/remoteproc \
drivers/regulator \
drivers/ras \
drivers/rapidio/switches \
drivers/rapidio \
drivers/rapidio/devices \
drivers/pwm \
drivers/ptp \
drivers/ps3 \
drivers/pps \
drivers/pps/generators \
drivers/pps/clients \
drivers/powercap \
drivers/power \
drivers/power/reset \
drivers/power/avs \
drivers/pnp \
drivers/pnp/pnpbios \
drivers/pnp/pnpacpi \
drivers/pnp/isapnp \
drivers/platform/x86 \
drivers/platform/olpc \
drivers/platform/mips \
drivers/platform/goldfish \
drivers/platform/chrome \
drivers/platform \
drivers/pinctrl/vt8500 \
drivers/pinctrl/uniphier \
drivers/pinctrl/sunxi \
drivers/pinctrl/spear \
drivers/pinctrl/sirf \
drivers/pinctrl/sh-pfc \
drivers/pinctrl/samsung \
drivers/pinctrl/qcom \
drivers/pinctrl \
drivers/pinctrl/nomadik \
drivers/pinctrl/mvebu \
drivers/pinctrl/meson \
drivers/pinctrl/mediatek \
drivers/pinctrl/intel \
drivers/pinctrl/freescale \
drivers/pinctrl/berlin \
drivers/pinctrl/bcm \
drivers/phy \
drivers/perf \
drivers/pcmcia \
drivers/pci \
drivers/pci/pcie \
drivers/pci/pcie/aer \
drivers/pci/hotplug \
drivers/pci/host \
drivers/parport \
drivers/parisc \
drivers/oprofile \
drivers/of \
drivers/nvmem \
drivers/nvme/host \
drivers/nvme \
drivers/nvdimm \
drivers/nubus \
drivers/ntb/test \
drivers/ntb \
drivers/ntb/hw/intel \
drivers/ntb/hw \
drivers/nfc \
drivers/nfc/st21nfca \
drivers/nfc/st-nci \
drivers/nfc/s3fwrn5 \
drivers/nfc/pn544 \
drivers/nfc/nxp-nci \
drivers/nfc/nfcmrvl \
drivers/nfc/microread \
drivers/nfc/fdp \
drivers/net \
drivers/net/xen-netback \
drivers/net/wireless/zd1211rw \
drivers/net/wireless \
drivers/net/wireless/ti/wlcore \
drivers/net/wireless/ti/wl18xx \
drivers/net/wireless/ti/wl12xx \
drivers/net/wireless/ti/wl1251 \
drivers/net/wireless/ti \
drivers/net/wireless/rt2x00 \
drivers/net/wireless/rsi \
drivers/net/wireless/realtek/rtlwifi \
drivers/net/wireless/realtek/rtlwifi/rtl8821ae \
drivers/net/wireless/realtek/rtlwifi/rtl8723com \
drivers/net/wireless/realtek/rtlwifi/rtl8723be \
drivers/net/wireless/realtek/rtlwifi/rtl8723ae \
drivers/net/wireless/realtek/rtlwifi/rtl8192se \
drivers/net/wireless/realtek/rtlwifi/rtl8192ee \
drivers/net/wireless/realtek/rtlwifi/rtl8192de \
drivers/net/wireless/realtek/rtlwifi/rtl8192cu \
drivers/net/wireless/realtek/rtlwifi/rtl8192ce \
drivers/net/wireless/realtek/rtlwifi/rtl8192c \
drivers/net/wireless/realtek/rtlwifi/rtl8188ee \
drivers/net/wireless/realtek/rtlwifi/btcoexist \
drivers/net/wireless/realtek/rtl8xxxu \
drivers/net/wireless/realtek/rtl818x/rtl8187 \
drivers/net/wireless/realtek/rtl818x/rtl8180 \
drivers/net/wireless/realtek/rtl818x \
drivers/net/wireless/realtek \
drivers/net/wireless/prism54 \
drivers/net/wireless/p54 \
drivers/net/wireless/orinoco \
drivers/net/wireless/mwifiex \
drivers/net/wireless/mediatek/mt7601u \
drivers/net/wireless/mediatek \
drivers/net/wireless/libertas_tf \
drivers/net/wireless/libertas \
drivers/net/wireless/iwlwifi/pcie \
drivers/net/wireless/iwlwifi/mvm \
drivers/net/wireless/iwlwifi \
drivers/net/wireless/iwlwifi/dvm \
drivers/net/wireless/iwlegacy \
drivers/net/wireless/ipw2x00 \
drivers/net/wireless/hostap \
drivers/net/wireless/cw1200 \
drivers/net/wireless/brcm80211 \
drivers/net/wireless/brcm80211/brcmutil \
drivers/net/wireless/brcm80211/brcmsmac \
drivers/net/wireless/brcm80211/brcmsmac/phy \
drivers/net/wireless/brcm80211/brcmfmac \
drivers/net/wireless/b43legacy \
drivers/net/wireless/b43 \
drivers/net/wireless/ath/wil6210 \
drivers/net/wireless/ath/wcn36xx \
drivers/net/wireless/ath \
drivers/net/wireless/ath/carl9170 \
drivers/net/wireless/ath/ath9k \
drivers/net/wireless/ath/ath6kl \
drivers/net/wireless/ath/ath5k \
drivers/net/wireless/ath/ath10k \
drivers/net/wireless/ath/ar5523 \
drivers/net/wimax/i2400m \
drivers/net/wimax \
drivers/net/wan \
drivers/net/wan/lmc \
drivers/net/vmxnet3 \
drivers/net/usb \
drivers/net/team \
drivers/net/slip \
drivers/net/ppp \
drivers/net/plip \
drivers/net/phy \
drivers/net/irda \
drivers/net/ipvlan \
drivers/net/ieee802154 \
drivers/net/hyperv \
drivers/net/hippi \
drivers/net/hamradio \
drivers/net/fjes \
drivers/net/fddi/skfp \
drivers/net/fddi \
drivers/net/ethernet/xscale \
drivers/net/ethernet/xircom \
drivers/net/ethernet/xilinx \
drivers/net/ethernet/wiznet \
drivers/net/ethernet/via \
drivers/net/ethernet/tundra \
drivers/net/ethernet/toshiba \
drivers/net/ethernet/tile \
drivers/net/ethernet/ti \
drivers/net/ethernet/tehuti \
drivers/net/ethernet/synopsys \
drivers/net/ethernet/sun \
drivers/net/ethernet/stmicro/stmmac \
drivers/net/ethernet/stmicro \
drivers/net/ethernet/smsc \
drivers/net/ethernet/sis \
drivers/net/ethernet/silan \
drivers/net/ethernet/sgi \
drivers/net/ethernet/sfc \
drivers/net/ethernet/seeq \
drivers/net/ethernet/samsung/sxgbe \
drivers/net/ethernet/samsung \
drivers/net/ethernet/rocker \
drivers/net/ethernet/renesas \
drivers/net/ethernet/realtek \
drivers/net/ethernet/rdc \
drivers/net/ethernet/qualcomm \
drivers/net/ethernet/qlogic/qlge \
drivers/net/ethernet/qlogic/qlcnic \
drivers/net/ethernet/qlogic \
drivers/net/ethernet/qlogic/qede \
drivers/net/ethernet/qlogic/qed \
drivers/net/ethernet/qlogic/netxen \
drivers/net/ethernet/pasemi \
drivers/net/ethernet/packetengines \
drivers/net/ethernet/oki-semi/pch_gbe \
drivers/net/ethernet/oki-semi \
drivers/net/ethernet/octeon \
drivers/net/ethernet/nxp \
drivers/net/ethernet/nvidia \
drivers/net/ethernet/nuvoton \
drivers/net/ethernet \
drivers/net/ethernet/neterion/vxge \
drivers/net/ethernet/neterion \
drivers/net/ethernet/natsemi \
drivers/net/ethernet/myricom/myri10ge \
drivers/net/ethernet/myricom \
drivers/net/ethernet/moxa \
drivers/net/ethernet/microchip \
drivers/net/ethernet/micrel \
drivers/net/ethernet/mellanox/mlxsw \
drivers/net/ethernet/mellanox/mlx5/core \
drivers/net/ethernet/mellanox/mlx4 \
drivers/net/ethernet/mellanox \
drivers/net/ethernet/marvell \
drivers/net/ethernet/intel/ixgbevf \
drivers/net/ethernet/intel/ixgbe \
drivers/net/ethernet/intel/ixgb \
drivers/net/ethernet/intel/igbvf \
drivers/net/ethernet/intel/igb \
drivers/net/ethernet/intel/i40evf \
drivers/net/ethernet/intel/i40e \
drivers/net/ethernet/intel/fm10k \
drivers/net/ethernet/intel/e1000e \
drivers/net/ethernet/intel/e1000 \
drivers/net/ethernet/intel \
drivers/net/ethernet/ibm \
drivers/net/ethernet/ibm/emac \
drivers/net/ethernet/ibm/ehea \
drivers/net/ethernet/i825xx \
drivers/net/ethernet/hp \
drivers/net/ethernet/hisilicon \
drivers/net/ethernet/hisilicon/hns \
drivers/net/ethernet/fujitsu \
drivers/net/ethernet/freescale \
drivers/net/ethernet/freescale/fs_enet \
drivers/net/ethernet/faraday \
drivers/net/ethernet/ezchip \
drivers/net/ethernet/emulex \
drivers/net/ethernet/emulex/benet \
drivers/net/ethernet/dlink \
drivers/net/ethernet/dec/tulip \
drivers/net/ethernet/dec \
drivers/net/ethernet/davicom \
drivers/net/ethernet/cisco/enic \
drivers/net/ethernet/cisco \
drivers/net/ethernet/cirrus \
drivers/net/ethernet/chelsio/cxgb4vf \
drivers/net/ethernet/chelsio/cxgb4 \
drivers/net/ethernet/chelsio/cxgb3 \
drivers/net/ethernet/chelsio/cxgb \
drivers/net/ethernet/chelsio \
drivers/net/ethernet/cavium/thunder \
drivers/net/ethernet/cavium/liquidio \
drivers/net/ethernet/cavium \
drivers/net/ethernet/calxeda \
drivers/net/ethernet/cadence \
drivers/net/ethernet/brocade \
drivers/net/ethernet/brocade/bna \
drivers/net/ethernet/broadcom \
drivers/net/ethernet/broadcom/genet \
drivers/net/ethernet/broadcom/bnxt \
drivers/net/ethernet/broadcom/bnx2x \
drivers/net/ethernet/aurora \
drivers/net/ethernet/atheros \
drivers/net/ethernet/atheros/atlx \
drivers/net/ethernet/atheros/atl1e \
drivers/net/ethernet/atheros/atl1c \
drivers/net/ethernet/atheros/alx \
drivers/net/ethernet/arc \
drivers/net/ethernet/apple \
drivers/net/ethernet/apm/xgene \
drivers/net/ethernet/amd/xgbe \
drivers/net/ethernet/amd \
drivers/net/ethernet/altera \
drivers/net/ethernet/alteon \
drivers/net/ethernet/allwinner \
drivers/net/ethernet/agere \
drivers/net/ethernet/aeroflex \
drivers/net/ethernet/adi \
drivers/net/ethernet/adaptec \
drivers/net/ethernet/8390 \
drivers/net/ethernet/3com \
drivers/net/dsa \
drivers/net/cris \
drivers/net/can \
drivers/net/can/usb \
drivers/net/can/usb/peak_usb \
drivers/net/can/spi \
drivers/net/can/softing \
drivers/net/can/sja1000 \
drivers/net/can/mscan \
drivers/net/can/m_can \
drivers/net/can/cc770 \
drivers/net/can/c_can \
drivers/net/caif \
drivers/net/bonding \
drivers/net/arcnet \
drivers/net/appletalk \
drivers/mtd/ubi \
drivers/mtd/tests \
drivers/mtd \
drivers/mtd/spi-nor \
drivers/mtd/onenand \
drivers/mtd/nand \
drivers/mtd/nand/gpmi-nand \
drivers/mtd/nand/brcmnand \
drivers/mtd/nand/bcm47xxnflash \
drivers/mtd/maps \
drivers/mtd/lpddr \
drivers/mtd/devices \
drivers/mtd/chips \
drivers/mmc/host \
drivers/mmc/core \
drivers/mmc/card \
drivers/mmc \
drivers/misc/vmw_vmci \
drivers/misc \
drivers/misc/ti-st \
drivers/misc/sgi-xp \
drivers/misc/sgi-gru \
drivers/misc/mic/scif \
drivers/misc/mic/host \
drivers/misc/mic/cosm_client \
drivers/misc/mic/cosm \
drivers/misc/mic/card \
drivers/misc/mic/bus \
drivers/misc/mic \
drivers/misc/mei \
drivers/misc/lis3lv02d \
drivers/misc/ibmasm \
drivers/misc/genwqe \
drivers/misc/eeprom \
drivers/misc/echo \
drivers/misc/cxl \
drivers/misc/cb710 \
drivers/misc/c2port \
drivers/misc/altera-stapl \
drivers/mfd \
drivers/message/fusion \
drivers/message \
drivers/memstick/host \
drivers/memstick/core \
drivers/memstick \
drivers/memory \
drivers/memory/tegra \
drivers/media/v4l2-core \
drivers/media/usb/zr364xx \
drivers/media/usb/uvc \
drivers/media/usb/usbvision \
drivers/media/usb/usbtv \
drivers/media/usb/ttusb-dec \
drivers/media/usb/ttusb-budget \
drivers/media/usb/tm6000 \
drivers/media/usb/stkwebcam \
drivers/media/usb/stk1160 \
drivers/media/usb/siano \
drivers/media/usb/s2255 \
drivers/media/usb/pwc \
drivers/media/usb/pvrusb2 \
drivers/media/usb/msi2500 \
drivers/media/usb/hdpvr \
drivers/media/usb/hackrf \
drivers/media/usb/gspca \
drivers/media/usb/gspca/stv06xx \
drivers/media/usb/gspca/m5602 \
drivers/media/usb/gspca/gl860 \
drivers/media/usb/go7007 \
drivers/media/usb/em28xx \
drivers/media/usb/dvb-usb-v2 \
drivers/media/usb/dvb-usb \
drivers/media/usb/cx231xx \
drivers/media/usb/cpia2 \
drivers/media/usb \
drivers/media/usb/b2c2 \
drivers/media/usb/au0828 \
drivers/media/usb/as102 \
drivers/media/usb/airspy \
drivers/media/tuners \
drivers/media/rc \
drivers/media/rc/keymaps \
drivers/media/rc/img-ir \
drivers/media/radio/wl128x \
drivers/media/radio \
drivers/media/radio/si4713 \
drivers/media/radio/si470x \
drivers/media/platform/xilinx \
drivers/media/platform/vsp1 \
drivers/media/platform/vivid \
drivers/media/platform \
drivers/media/platform/ti-vpe \
drivers/media/platform/sti/c8sectpfe \
drivers/media/platform/sti/bdisp \
drivers/media/platform/soc_camera \
drivers/media/platform/s5p-tv \
drivers/media/platform/s5p-mfc \
drivers/media/platform/s5p-jpeg \
drivers/media/platform/s5p-g2d \
drivers/media/platform/s3c-camif \
drivers/media/platform/omap3isp \
drivers/media/platform/omap \
drivers/media/platform/marvell-ccic \
drivers/media/platform/exynos4-is \
drivers/media/platform/exynos-gsc \
drivers/media/platform/davinci \
drivers/media/platform/coda \
drivers/media/platform/blackfin \
drivers/media/platform/am437x \
drivers/media/pci/zoran \
drivers/media/pci/tw68 \
drivers/media/pci/ttpci \
drivers/media/pci/sta2x11 \
drivers/media/pci/solo6x10 \
drivers/media/pci/smipcie \
drivers/media/pci/saa7164 \
drivers/media/pci/saa7146 \
drivers/media/pci/saa7134 \
drivers/media/pci/pt3 \
drivers/media/pci/pt1 \
drivers/media/pci/pluto2 \
drivers/media/pci/ngene \
drivers/media/pci/netup_unidvb \
drivers/media/pci/meye \
drivers/media/pci/mantis \
drivers/media/pci/ivtv \
drivers/media/pci/dt3155 \
drivers/media/pci/dm1105 \
drivers/media/pci/ddbridge \
drivers/media/pci/cx88 \
drivers/media/pci/cx25821 \
drivers/media/pci/cx23885 \
drivers/media/pci/cx18 \
drivers/media/pci/cobalt \
drivers/media/pci \
drivers/media/pci/bt8xx \
drivers/media/pci/b2c2 \
drivers/media/mmc/siano \
drivers/media/mmc \
drivers/media \
drivers/media/i2c \
drivers/media/i2c/soc_camera \
drivers/media/i2c/smiapp \
drivers/media/i2c/s5c73m3 \
drivers/media/i2c/m5mols \
drivers/media/i2c/cx25840 \
drivers/media/firewire \
drivers/media/dvb-frontends \
drivers/media/dvb-frontends/drx39xyj \
drivers/media/dvb-core \
drivers/media/common \
drivers/media/common/siano \
drivers/media/common/saa7146 \
drivers/media/common/b2c2 \
drivers/md \
drivers/md/persistent-data \
drivers/md/bcache \
drivers/mcb \
drivers/mailbox \
drivers/macintosh \
drivers/macintosh/ams \
drivers/lightnvm \
drivers/lguest/x86 \
drivers/lguest \
drivers/leds/trigger \
drivers/leds \
drivers/isdn/sc \
drivers/isdn/pcbit \
drivers/isdn/mISDN \
drivers/isdn/isdnloop \
drivers/isdn/icn \
drivers/isdn/i4l \
drivers/isdn/hysdn \
drivers/isdn/hisax \
drivers/isdn/hardware/mISDN \
drivers/isdn/hardware/eicon \
drivers/isdn/hardware \
drivers/isdn/hardware/avm \
drivers/isdn/gigaset \
drivers/isdn/divert \
drivers/isdn/capi \
drivers/isdn \
drivers/isdn/act2000 \
drivers/irqchip \
drivers/ipack \
drivers/ipack/devices \
drivers/ipack/carriers \
drivers/iommu \
drivers/input/touchscreen \
drivers/input/tablet \
drivers/input \
drivers/input/serio \
drivers/input/mouse \
drivers/input/misc \
drivers/input/keyboard \
drivers/input/joystick \
drivers/input/joystick/iforce \
drivers/input/gameport \
drivers/infiniband/ulp/srpt \
drivers/infiniband/ulp/srp \
drivers/infiniband/ulp/isert \
drivers/infiniband/ulp/iser \
drivers/infiniband/ulp/ipoib \
drivers/infiniband/ulp \
drivers/infiniband/hw/usnic \
drivers/infiniband/hw/qib \
drivers/infiniband/hw/ocrdma \
drivers/infiniband/hw/nes \
drivers/infiniband/hw/mthca \
drivers/infiniband/hw/mlx5 \
drivers/infiniband/hw/mlx4 \
drivers/infiniband/hw/cxgb4 \
drivers/infiniband/hw/cxgb3 \
drivers/infiniband/hw \
drivers/infiniband/core \
drivers/infiniband \
drivers/iio/trigger \
drivers/iio/temperature \
drivers/iio/proximity \
drivers/iio/pressure \
drivers/iio/potentiometer \
drivers/iio/orientation \
drivers/iio/magnetometer \
drivers/iio/light \
drivers/iio \
drivers/iio/imu \
drivers/iio/imu/inv_mpu6050 \
drivers/iio/humidity \
drivers/iio/gyro \
drivers/iio/frequency \
drivers/iio/dac \
drivers/iio/common/st_sensors \
drivers/iio/common/ssp_sensors \
drivers/iio/common/ms_sensors \
drivers/iio/common/hid-sensors \
drivers/iio/common \
drivers/iio/chemical \
drivers/iio/buffer \
drivers/iio/amplifiers \
drivers/iio/adc \
drivers/iio/accel \
drivers/idle \
drivers/ide \
drivers/i2c/muxes \
drivers/i2c \
drivers/i2c/busses \
drivers/i2c/algos \
drivers/hwtracing/stm \
drivers/hwtracing/intel_th \
drivers/hwtracing/coresight \
drivers/hwspinlock \
drivers/hwmon \
drivers/hwmon/pmbus \
drivers/hv \
drivers/hsi \
drivers/hsi/controllers \
drivers/hsi/clients \
drivers/hid \
drivers/hid/usbhid \
drivers/hid/i2c-hid \
drivers/gpu/vga \
drivers/gpu/ipu-v3 \
drivers/gpu/host1x \
drivers/gpu/host1x/hw \
drivers/gpu/drm/vmwgfx \
drivers/gpu/drm/virtio \
drivers/gpu/drm/via \
drivers/gpu/drm/vgem \
drivers/gpu/drm/vc4 \
drivers/gpu/drm/udl \
drivers/gpu/drm/ttm \
drivers/gpu/drm/tilcdc \
drivers/gpu/drm/tegra \
drivers/gpu/drm/tdfx \
drivers/gpu/drm/sti \
drivers/gpu/drm/sis \
drivers/gpu/drm/shmobile \
drivers/gpu/drm/savage \
drivers/gpu/drm/rockchip \
drivers/gpu/drm/rcar-du \
drivers/gpu/drm/radeon \
drivers/gpu/drm/r128 \
drivers/gpu/drm/qxl \
drivers/gpu/drm/panel \
drivers/gpu/drm/omapdrm \
drivers/gpu/drm/nouveau/nvkm/subdev/volt \
drivers/gpu/drm/nouveau/nvkm/subdev/timer \
drivers/gpu/drm/nouveau/nvkm/subdev/therm \
drivers/gpu/drm/nouveau/nvkm/subdev/pmu \
drivers/gpu/drm/nouveau/nvkm/subdev/pci \
drivers/gpu/drm/nouveau/nvkm/subdev/mxm \
drivers/gpu/drm/nouveau/nvkm/subdev/mmu \
drivers/gpu/drm/nouveau/nvkm/subdev/mc \
drivers/gpu/drm/nouveau/nvkm/subdev/ltc \
drivers/gpu/drm/nouveau/nvkm/subdev/instmem \
drivers/gpu/drm/nouveau/nvkm/subdev/ibus \
drivers/gpu/drm/nouveau/nvkm/subdev/i2c \
drivers/gpu/drm/nouveau/nvkm/subdev/gpio \
drivers/gpu/drm/nouveau/nvkm/subdev/fuse \
drivers/gpu/drm/nouveau/nvkm/subdev/fb \
drivers/gpu/drm/nouveau/nvkm/subdev/devinit \
drivers/gpu/drm/nouveau/nvkm/subdev/clk \
drivers/gpu/drm/nouveau/nvkm/subdev/bus \
drivers/gpu/drm/nouveau/nvkm/subdev/bios \
drivers/gpu/drm/nouveau/nvkm/subdev/bar \
drivers/gpu/drm/nouveau/nvkm/engine \
drivers/gpu/drm/nouveau/nvkm/engine/vp \
drivers/gpu/drm/nouveau/nvkm/engine/sw \
drivers/gpu/drm/nouveau/nvkm/engine/sec \
drivers/gpu/drm/nouveau/nvkm/engine/pm \
drivers/gpu/drm/nouveau/nvkm/engine/msvld \
drivers/gpu/drm/nouveau/nvkm/engine/msppp \
drivers/gpu/drm/nouveau/nvkm/engine/mspdec \
drivers/gpu/drm/nouveau/nvkm/engine/mpeg \
drivers/gpu/drm/nouveau/nvkm/engine/gr \
drivers/gpu/drm/nouveau/nvkm/engine/fifo \
drivers/gpu/drm/nouveau/nvkm/engine/dma \
drivers/gpu/drm/nouveau/nvkm/engine/disp \
drivers/gpu/drm/nouveau/nvkm/engine/device \
drivers/gpu/drm/nouveau/nvkm/engine/cipher \
drivers/gpu/drm/nouveau/nvkm/engine/ce \
drivers/gpu/drm/nouveau/nvkm/engine/bsp \
drivers/gpu/drm/nouveau/nvkm/core \
drivers/gpu/drm/nouveau/nvif \
drivers/gpu/drm/nouveau \
drivers/gpu/drm/nouveau/dispnv04 \
drivers/gpu/drm/msm \
drivers/gpu/drm/msm/mdp \
drivers/gpu/drm/msm/mdp/mdp5 \
drivers/gpu/drm/msm/mdp/mdp4 \
drivers/gpu/drm/msm/hdmi \
drivers/gpu/drm/msm/edp \
drivers/gpu/drm/msm/dsi/pll \
drivers/gpu/drm/msm/dsi/phy \
drivers/gpu/drm/msm/dsi \
drivers/gpu/drm/msm/adreno \
drivers/gpu/drm/mgag200 \
drivers/gpu/drm/mga \
drivers/gpu/drm/imx \
drivers/gpu/drm/i915 \
drivers/gpu/drm/i810 \
drivers/gpu/drm/i2c \
drivers/gpu/drm/gma500 \
drivers/gpu/drm/fsl-dcu \
drivers/gpu/drm/exynos \
drivers/gpu/drm \
drivers/gpu/drm/cirrus \
drivers/gpu/drm/bridge \
drivers/gpu/drm/bochs \
drivers/gpu/drm/atmel-hlcdc \
drivers/gpu/drm/ast \
drivers/gpu/drm/armada \
drivers/gpu/drm/amd/scheduler \
drivers/gpu/drm/amd/amdkfd \
drivers/gpu/drm/amd/amdgpu \
drivers/gpu \
drivers/gpio \
drivers/fpga \
drivers/fmc \
drivers/firmware \
drivers/firmware/google \
drivers/firmware/efi \
drivers/firmware/efi/libstub \
drivers/firmware/broadcom \
drivers/firewire \
drivers/extcon \
drivers/eisa \
drivers/edac \
drivers/dma-buf \
drivers/dma \
drivers/dma/xilinx \
drivers/dma/sh \
drivers/dma/ppc4xx \
drivers/dma/ipu \
drivers/dma/ioat \
drivers/dma/hsu \
drivers/dma/dw \
drivers/dma/bestcomm \
drivers/dio \
drivers/devfreq \
drivers/devfreq/exynos \
drivers/devfreq/event \
drivers/dca \
drivers/crypto/vmx \
drivers/crypto/ux500/hash \
drivers/crypto/ux500/cryp \
drivers/crypto \
drivers/crypto/sunxi-ss \
drivers/crypto/qce \
drivers/crypto/qat/qat_dh895xccvf \
drivers/crypto/qat/qat_dh895xcc \
drivers/crypto/qat/qat_common \
drivers/crypto/qat \
drivers/crypto/nx \
drivers/crypto/marvell \
drivers/crypto/ccp \
drivers/crypto/caam \
drivers/crypto/amcc \
drivers/cpuidle \
drivers/cpuidle/governors \
drivers/cpufreq \
drivers/connector \
drivers/clocksource \
drivers/clk/zynq \
drivers/clk/zte \
drivers/clk/x86 \
drivers/clk/versatile \
drivers/clk/ux500 \
drivers/clk/ti \
drivers/clk/tegra \
drivers/clk/sunxi \
drivers/clk/st \
drivers/clk/spear \
drivers/clk/socfpga \
drivers/clk/sirf \
drivers/clk/shmobile \
drivers/clk/samsung \
drivers/clk/rockchip \
drivers/clk/qcom \
drivers/clk/pxa \
drivers/clk/pistachio \
drivers/clk/nxp \
drivers/clk/mxs \
drivers/clk/mvebu \
drivers/clk/mmp \
drivers/clk/meson \
drivers/clk/mediatek \
drivers/clk/keystone \
drivers/clk/ingenic \
drivers/clk/imx \
drivers/clk/hisilicon \
drivers/clk/h8300 \
drivers/clk \
drivers/clk/berlin \
drivers/clk/bcm \
drivers/clk/at91 \
drivers/char/xillybus \
drivers/char/xilinx_hwicap \
drivers/char \
drivers/char/tpm \
drivers/char/tpm/st33zp24 \
drivers/char/pcmcia \
drivers/char/mwave \
drivers/char/ipmi \
drivers/char/hw_random \
drivers/char/agp \
drivers/cdrom \
drivers/bus \
drivers \
drivers/bluetooth \
drivers/block/zram \
drivers/block \
drivers/block/xen-blkback \
drivers/block/rsxx \
drivers/block/paride \
drivers/block/mtip32xx \
drivers/block/drbd \
drivers/block/aoe \
drivers/bcma \
drivers/base \
drivers/base/regmap \
drivers/base/power \
drivers/base/power/opp \
drivers/auxdisplay \
drivers/atm \
drivers/ata \
drivers/android \
drivers/amba \
drivers/acpi \
drivers/acpi/pmic \
drivers/acpi/apei \
drivers/acpi/acpica \
drivers/accessibility/braille \
crypto \
crypto/async_tx \
crypto/asymmetric_keys \
certs \
block \
block/partitions \
arch/x86/xen \
arch/x86/video \
arch/x86/um/vdso \
arch/x86/um \
arch/x86/um/os-Linux \
arch/x86/tools \
arch/x86/realmode \
arch/x86/realmode/rm \
arch/x86/ras \
arch/x86/purgatory \
arch/x86/power \
arch/x86/platform/uv \
arch/x86/platform/ts5500 \
arch/x86/platform/sfi \
arch/x86/platform/scx200 \
arch/x86/platform/olpc \
arch/x86/platform/iris \
arch/x86/platform/intel-quark \
arch/x86/platform/intel-mid \
arch/x86/platform/intel-mid/device_libs \
arch/x86/platform/intel \
arch/x86/platform/goldfish \
arch/x86/platform/geode \
arch/x86/platform/efi \
arch/x86/platform/ce4100 \
arch/x86/platform \
arch/x86/platform/atom \
arch/x86/pci \
arch/x86/oprofile \
arch/x86/net \
arch/x86/mm \
arch/x86/mm/kmemcheck \
arch/x86/math-emu \
arch/x86/lib \
arch/x86/lguest \
arch/x86/kvm \
arch/x86/kernel \
arch/x86/kernel/kprobes \
arch/x86/kernel/fpu \
arch/x86/kernel/cpu \
arch/x86/kernel/cpu/mtrr \
arch/x86/kernel/cpu/microcode \
arch/x86/kernel/cpu/mcheck \
arch/x86/kernel/apic \
arch/x86/kernel/acpi \
arch/x86/ia32 \
arch/x86/entry/vsyscall \
arch/x86/entry/vdso \
arch/x86/entry/vdso/vdso32 \
arch/x86/entry \
arch/x86/crypto \
arch/x86/crypto/sha-mb \
arch/x86 \
arch/x86/boot \
arch/x86/boot/tools \
arch/x86/boot/compressed \
Documentation/watchdog/src \
Documentation/video4linux \
Documentation/vDSO \
Documentation/timers \
Documentation/spi \
Documentation/ptp \
Documentation/prctl \
Documentation/pcmcia \
Documentation/networking/timestamping \
Documentation/misc-devices/mei \
Documentation/laptops \
Documentation/ia64 \
Documentation/filesystems \
Documentation/connector \
Documentation/blackfin \
Documentation/auxdisplay \
Documentation/accounting \
Documentation/EDID \

